
sudo: required
dist: trusty
language: node_js
node_js:
  - '8.9.4'

services:
  - docker

env:
    global:
    - PATH=$PATH:$HOME/google-cloud-sdk/bin
    - PROJECT_ID="snappy-sunset-198621"
    - ZONE="us-central1-a"
    - IMAGE_NAME=quote-of-the-day:latest
    - FULL_IMAGE_NAME=gcr.io/$PROJECT_ID/$IMAGE_NAME
    - GOOGLE_APPLICATION_CREDENTIALS="${PWD}/quote_of_the_day_fe0bf392a335.json"
    - CLUSTER_NAME="quote-of-the-day-prod"

apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

cache:
  directories:
    - "$HOME/google-cloud-sdk/"

install:
#NPM install
- npm install -g angular-cli
- npm install -g karma
- npm install
- ng build

#Google cloud SDK installation and configution
- if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash > /dev/null; fi
- source /home/travis/google-cloud-sdk/path.bash.inc
- gcloud version

# Update Kubernetes
- gcloud --quiet components update
- gcloud --quiet components update kubectl

# Generate credential file
- openssl aes-256-cbc -K $encrypted_940145a3ff79_key -iv $encrypted_940145a3ff79_iv -in quote_of_the_day_fe0bf392a335.json.enc -out quote_of_the_day_fe0bf392a335.json -d

# Configurar credenciales de GCloud
- gcloud --quiet auth activate-service-account --key-file "${GOOGLE_APPLICATION_CREDENTIALS}"

# Conseguir crendeciales para Kubernetes
- gcloud --quiet config set project $PROJECT_ID
- gcloud --quiet config set container/cluster $CLUSTER_NAME
- gcloud --quiet config set compute/zone ${ZONE}
- gcloud --quiet config set container/use_application_default_credentials true
- gcloud --quiet config set container/use_client_certificate true
- gcloud --quiet container clusters get-credentials $CLUSTER_NAME

before_script:
# Preparando el ambiente para correr los tests con karma
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start

script: 
- karma start karma.conf.js --single-run

after_success:
# Preparacion el container y lo subimos al repositorio privado
- docker build --no-cache=true -t $FULL_IMAGE_NAME .
- gcloud docker -- push $FULL_IMAGE_NAME

# Instalando deployment y service.
- ./create-service.sh
- ./create-deploy.sh