
sudo: required
dist: trusty
language: node_js
node_js:
  - '8.9.4'

services:
  - docker

env:
    global:
    - PATH=$PATH:$HOME/google-cloud-sdk/bin
    - PROJECT_ID="snappy-sunset-198621"
    - ZONE="us-central1-a"
    - IMAGE_NAME=quote-of-the-day:latest
    - FULL_IMAGE_NAME=gcr.io/$PROJECT_ID/$IMAGE_NAME
    - GOOGLE_APPLICATION_CREDENTIALS="${PWD}/quote_of_the_day_fe0bf392a335.json"
    - CLUSTER_NAME="quote-of-the-day-prod"
    - SA_NAME=quote-of-the-day-deployment
    - SA_EMAIL=$SA_NAME@$snappy-sunset-198621.iam.gserviceaccount.com

apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

cache:
  directories:
    - "$HOME/google-cloud-sdk/"

install:
#NPM install
- npm install -g angular-cli
- npm install -g karma
- npm install
- ng build

#Google cloud SDK installation and configution
- if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash > /dev/null; fi
- source /home/travis/google-cloud-sdk/path.bash.inc
- gcloud --quiet components update
- gcloud --quiet components update kubectl
- openssl aes-256-cbc -K $encrypted_940145a3ff79_key -iv $encrypted_940145a3ff79_iv -in quote_of_the_day_fe0bf392a335.json.enc -out quote_of_the_day_fe0bf392a335.json -d
- gcloud config set project $PROJECT_ID
- gcloud config set compute/zone $ZONE

# Create a new GCP IAM service account.
- gcloud iam service-accounts create $SA_NAME

# Download a json key for that service account.
- gcloud iam service-accounts keys create $GOOGLE_APPLICATION_CREDENTIALS --iam-account $SA_EMAIL

# Give that service account the "Container Engine Developer" IAM role for your project.
- gcloud projects add-iam-policy-binding $PROJECT_ID --member serviceAccount:$SA_EMAIL --role roles/container.developer

before_script:
# Preparando el ambiente para correr los tests con karma
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start

script: 
- karma start karma.conf.js --single-run

after_success:
# Preparacion el container y lo subimos al repositorio privado
- docker build --no-cache=true -t $FULL_IMAGE_NAME .
- gcloud docker -- push $FULL_IMAGE_NAME

# Configure kubectl to point to your cluster.
gcloud container clusters get-credentials $CLUSTER_NAME

# Configure Application Default Credentials (what kubectl uses) to use the service account.
export GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_APPLICATION_CREDENTIALS

- kubectl create -f quote-of-the-day-deployment.yaml
- kubectl create -f quote-of-the-day-service.yaml