apiVersion: v1
kind: Service
metadata:
  name: quote-svc
  labels:
    app: quote-of-the-day
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    nodePort: 30001
    protocol: TCP
  selector:
    app: quote-of-the-day